### ISSUE TITLE
Ständige Logs im Grundsystem

### ISSUE THREAD

**Issue by bumerang24** [zencartpro/157-modul-uid#1]
Hallo Webchills,

ich komme leider nicht voran mit dem Problem, egal was ich mache.
Es kommt immer folgendes Log im Grundsystem:

[03-Sep-2022 20:01:01 Europe/Berlin] Request URI: /index.php?main_page=index, IP address: 62.
#1 RiCjLoaderPlugin->autoloadLoaders() called at [/includes/templates/responsive_classic/common/html_header.php:99]
#2 require(/includes/templates/responsive_classic/common/html_header.php) called at [/index.php:43]
--> PHP Notice: Undefined variable: loaders in /extras/plugins/riCjLoader/RiCjLoaderPlugin.php on line 88.

Ich hab den kompletten Loader schon getauscht, Erfolg es ging gar nichts mehr.

Der Shop hat nur einen Testartikel in einer Test-Kategorie.
Das Log kommt mit PHP7.4 und 8.0

Ich würde gerne mal auch wissen, wie man mit den Issues in die richtige Kategorie kommt, es geht ja hier um das Grundsystem.

**Comment by webchills** [comment]
Hier ist das Repository für das UID Modul. Hier geht es darum Fehler im UID Modul zu dokumentieren. Wenn Du Fehler im Grundsystem melden willst, dann gehst Du ins Repository des Grundsystems https://github.com/zencartpro/zencart-german-grundsystem und dort auf Issues. Das gepostete Logfile mit irgendeiner völlig harmlosen Notice ist kein Fehler, muss nicht als Issue gemeldet werden. Bitte beschränke Dich auf echte Fehler, eine solche Notice ist keiner:
https://www.zen-cart-pro.at/knowledgebase/bedeutung-von-notice-warning-und-error-in-den-zen-cart-debug-logs/
